# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install --dev
    - name: Lint with Pylint
      run: |
        pipenv run pylint ./src ./tests
    - name: Check types with mypy
      run: |
        pipenv run mypy ./src ./tests
    - name: Check for docstrings with pydocstyle
      run: |
        pipenv run pydocstyle ./src ./tests
    - name: Check propper import order with isort
      run: |
        pipenv run isort --check-only --diff ./src ./tests
    - name: Test with unittest and report code coverage
      run: |
        pipenv run coverage run -m unittest discover -v -s ./tests -p 'test_*.py'
